version: "3.3"

volumes:
  db_api:
  db_admin:
  static_volume:
  media_volume:




services:
  postgres_db:
    image: postgres:16.3
    volumes:
      - db_api:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env


  admin_db:
    image: postgres:16.3
    volumes:
      - db_admin:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env.unfold
    ports:
      - "3004:80"


  api: &api
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres_db
    restart: always
    command: make run-docker
    env_file:
      - ./.env
    volumes:
      - media_volume:/usr/src/app/media

  admin:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: make unfold-docker
    env_file:
      ./.env
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    depends_on:
    - admin_db


  nginx:
    build: 
      context: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - 3004:80
    depends_on:
      - api
      - admin


  migrator:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - admin_db
      - postgres_db
    command: make run-migrator-docker
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    env_file:
      - ./.env

