version: "3.3"

volumes:
  db_api:
  db_admin:
  local_static_data:

services:
  postgres_db:
    image: postgres:16.3
    volumes:
      - db_api:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env


  admin_db:
    image: postgres:16.3
    volumes:
      - db_admin:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env.unfold


  api: &api
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres_db
    restart: always
    command: make run-docker
    ports:
      - "8000:8000"
    env_file:
      - ./.env


  admin:
    # <<: *api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: make unfold-docker
    env_file:
      ./.env
    volumes:
      - local_static_data:/usr/src/app/staticfiles
    depends_on:
    - admin_db
    ports:
      - "8001:8000"



  migrator:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - admin_db
      - postgres_db
    command: make run-migrator-docker
    volumes:
      - local_static_data:/usr/src/app/staticfiles
    env_file:
      - ./.env

