"""(1) add subscribtion status

Revision ID: 88a7fbea065f
Revises: 1d21c6f48c5b
Create Date: 2024-11-15 11:33:38.397579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88a7fbea065f'
down_revision: Union[str, None] = '1d21c6f48c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('subscriptions', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('subscriptions', 'is_active')
    # ### end Alembic commands ###
