"""MTM with categoryes and notification entities

Revision ID: 6f99feaa2a3a
Revises: e92dcb009c43
Create Date: 2024-12-24 12:48:18.715684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f99feaa2a3a'
down_revision: Union[str, None] = 'e92dcb009c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_credential',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registraion_token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_notification_credetial',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('notification_credential_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['notification_credential_id'], ['notification_credential.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'notification_credential_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_notification_credetial')
    op.drop_table('notification_credential')
    # ### end Alembic commands ###
