"""I have add field with sections type

Revision ID: dfd878769211
Revises: d6d5c09fc188
Create Date: 2024-10-24 15:44:48.131915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd878769211'
down_revision: Union[str, None] = 'd6d5c09fc188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_section_with_slide_show', sa.Column('section_type', sa.String(length=50), nullable=False))
    op.add_column('article_section_with_video', sa.Column('section_type', sa.String(length=50), nullable=False))
    op.add_column('article_sections_with_plain_text', sa.Column('section_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_sections_with_plain_text', 'section_type')
    op.drop_column('article_section_with_video', 'section_type')
    op.drop_column('article_section_with_slide_show', 'section_type')
    # ### end Alembic commands ###
