"""changes in article sections - delete inheritange

Revision ID: 4a789d0263e4
Revises: ba13273a3618
Create Date: 2024-09-26 20:49:22.039223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a789d0263e4'
down_revision: Union[str, None] = 'ba13273a3618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_section_with_slide_show', sa.Column('article_id', sa.Integer(), nullable=True))
    op.add_column('article_section_with_slide_show', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('article_section_with_slide_show', sa.Column('intex_number_in_article', sa.Integer(), nullable=False))
    op.drop_constraint('article_section_with_slide_show_id_fkey', 'article_section_with_slide_show', type_='foreignkey')
    op.create_foreign_key(None, 'article_section_with_slide_show', 'articles', ['article_id'], ['id'])
    op.add_column('article_section_with_video', sa.Column('article_id', sa.Integer(), nullable=True))
    op.add_column('article_section_with_video', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('article_section_with_video', sa.Column('intex_number_in_article', sa.Integer(), nullable=False))
    op.drop_constraint('article_section_with_video_id_fkey', 'article_section_with_video', type_='foreignkey')
    op.create_foreign_key(None, 'article_section_with_video', 'articles', ['article_id'], ['id'])
    op.add_column('article_sections_with_plain_text', sa.Column('article_id', sa.Integer(), nullable=True))
    op.add_column('article_sections_with_plain_text', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('article_sections_with_plain_text', sa.Column('intex_number_in_article', sa.Integer(), nullable=False))
    op.drop_constraint('article_sections_with_plain_text_id_fkey', 'article_sections_with_plain_text', type_='foreignkey')
    op.create_foreign_key(None, 'article_sections_with_plain_text', 'articles', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_sections_with_plain_text', type_='foreignkey')
    op.create_foreign_key('article_sections_with_plain_text_id_fkey', 'article_sections_with_plain_text', 'article_sections', ['id'], ['id'])
    op.drop_column('article_sections_with_plain_text', 'intex_number_in_article')
    op.drop_column('article_sections_with_plain_text', 'text')
    op.drop_column('article_sections_with_plain_text', 'article_id')
    op.drop_constraint(None, 'article_section_with_video', type_='foreignkey')
    op.create_foreign_key('article_section_with_video_id_fkey', 'article_section_with_video', 'article_sections', ['id'], ['id'])
    op.drop_column('article_section_with_video', 'intex_number_in_article')
    op.drop_column('article_section_with_video', 'text')
    op.drop_column('article_section_with_video', 'article_id')
    op.drop_constraint(None, 'article_section_with_slide_show', type_='foreignkey')
    op.create_foreign_key('article_section_with_slide_show_id_fkey', 'article_section_with_slide_show', 'article_sections', ['id'], ['id'])
    op.drop_column('article_section_with_slide_show', 'intex_number_in_article')
    op.drop_column('article_section_with_slide_show', 'text')
    op.drop_column('article_section_with_slide_show', 'article_id')
    # ### end Alembic commands ###
