"""adding main image in article pbject

Revision ID: d6d5c09fc188
Revises: 78046ba55e7f
Create Date: 2024-10-23 12:23:04.914136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d5c09fc188'
down_revision: Union[str, None] = '78046ba55e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('main_image', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'main_image')
    # ### end Alembic commands ###
