"""change strhucture of image file

Revision ID: ce0f0bdd835f
Revises: df56ca8f1a95
Create Date: 2024-10-14 13:58:02.864609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from src.infrastructure.database.utilities.save_file_field import SaveFileField

# revision identifiers, used by Alembic.
revision: str = 'ce0f0bdd835f'
down_revision: Union[str, None] = 'df56ca8f1a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_section_with_slide_show', 'image',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=SaveFileField(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_section_with_slide_show', 'image',
               existing_type=SaveFileField(length=255),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
