"""initial migration

Revision ID: cc55504411cc
Revises: 
Create Date: 2024-09-22 23:06:09.701259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy
import sqlalchemy_file

# revision identifiers, used by Alembic.
revision: str = 'cc55504411cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('quantity_of_search_requests', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unregistered_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.Enum('Ios', 'Android', name='device_type'), nullable=False),
    sa.Column('readed_articles', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('lead', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('publication_date', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expiration_date', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('subscription_type', sa.Enum('PREMIUM', 'PLUS', name='subscription_type'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('article_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intex_number_in_article', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_section_with_slide_show',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image', sqlalchemy_file.types.FileField(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['article_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_section_with_video',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['article_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_sections_with_plain_text',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['article_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_sections_with_plain_text')
    op.drop_table('article_section_with_video')
    op.drop_table('article_section_with_slide_show')
    op.drop_table('comments')
    op.drop_table('article_sections')
    op.drop_table('subscriptions')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('unregistered_devices')
    op.drop_table('search_request')
    op.drop_table('category')
    # ### end Alembic commands ###
