"""add index in title and lead

Revision ID: 2423be6b83f8
Revises: 4862e5b1afee
Create Date: 2024-11-19 16:24:59.688961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2423be6b83f8'
down_revision: Union[str, None] = '4862e5b1afee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title_index', 'articles', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title_index', table_name='articles')
    # ### end Alembic commands ###
