"""delete subscription-comments entity

Revision ID: f43cb77af7a6
Revises: 0ae47a4aeff7
Create Date: 2024-10-15 10:27:02.168580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43cb77af7a6'
down_revision: Union[str, None] = '0ae47a4aeff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
