"""add transactions

Revision ID: 8bd04c3b2cb3
Revises: 488c284620e4
Create Date: 2025-02-14 12:58:38.457871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd04c3b2cb3'
down_revision: Union[str, None] = '488c284620e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('IN_PROCESS', 'SUCCESS', 'FAIL', 'TEST', name='transaction_status'), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
