"""transaction is not unique

Revision ID: acbca46e2fed
Revises: 6d272139fc1a
Create Date: 2025-02-13 18:51:14.985708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbca46e2fed'
down_revision: Union[str, None] = '6d272139fc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_subscription_id_key', 'transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('transactions_subscription_id_key', 'transactions', ['subscription_id'])
    # ### end Alembic commands ###
