"""add new field in user

Revision ID: a1070cf7d1cb
Revises: 508adc4f3c61
Create Date: 2025-03-22 18:17:29.530036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1070cf7d1cb'
down_revision: Union[str, None] = '508adc4f3c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_registered_throw_google', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_registered_throw_google')
    # ### end Alembic commands ###
