"""add in_active in notification credential entity

Revision ID: 8ace87e71c87
Revises: 6f99feaa2a3a
Create Date: 2025-02-01 18:16:06.669058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ace87e71c87'
down_revision: Union[str, None] = '6f99feaa2a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_credential', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_credential', 'is_active')
    # ### end Alembic commands ###
