"""add tarifs

Revision ID: 488c284620e4
Revises: 19115d351a11
Create Date: 2025-02-12 14:29:51.675176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488c284620e4'
down_revision: Union[str, None] = '19115d351a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subscription_period', sa.Enum('WEEK', 'MONTH', 'YEAR', name='subscription_period'), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_per_year', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('curency', sa.Enum('EUR', 'USD', 'UAH', name='curency_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tariff')
    # ### end Alembic commands ###
