"""add tariff in transaction objects

Revision ID: 4e8971f389da
Revises: 8bd04c3b2cb3
Create Date: 2025-02-15 16:15:02.818946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8971f389da'
down_revision: Union[str, None] = '8bd04c3b2cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tariff_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'tariff', ['tariff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'tariff_id')
    # ### end Alembic commands ###
